#!/bin/sh
set -eu

# Iron Linux Login Greeter Autostart
# Display login-background branding under gtkgreet
wallpaper=/usr/share/backgrounds/iron/login-background.png
if [ -r "$wallpaper" ]; then
    swaybg -m fill -i "$wallpaper" &
else
    swaybg -c '#111315' &
fi

gtkgreet -l -s /etc/greetd/style.css
labwc --exit
