---
mountOptions:
  default: defaults,noatime
  ext4: defaults,noatime,errors=remount-ro
  btrfs: defaults,noatime,compress=zstd:3
ssdExtraMountOptions:
  ext4: discard
  xfs: discard
  swap: discard
  btrfs: discard
crypttabOptions: luks,discard,keyscript=/bin/cat
