---
efi:
  mountPoint: "/boot/efi"
  recommendedSize: 512MiB
  minimumSize: 300MiB
  label: "EFI"

userSwapChoices:
  - none
  - small
  - suspend
  - file

luksGeneration: luks2
drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "xfs", "btrfs"]
essentialMounts: ["live-*", "control", "ventoy"]

lvm:
  enable: false

partitionLayout:
  - name: "iron-root"
    filesystem: "ext4"
    mountPoint: "/"
    size: 100%
    minSize: 10GiB
